
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\charl\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\FINAL\assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("300x400")
window.configure(bg = "#FFDB00")


canvas = Canvas(
    window,
    bg = "#FFDB00",
    height = 400,
    width = 300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)


button_image_1 = PhotoImage(
    file=relative_to_assets("add_employee_database.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=138.0,
    y=332.0,
    width=117.0,
    height=24.0
)

canvas.create_text(
    19.0,
    153.0,
    anchor="nw",
    text="First Name:",
    fill="#0B2F9F",
    font=("Times New Roman Bold", 15 * -1)
)

canvas.create_text(
    21.0,
    191.0,
    anchor="nw",
    text="Last Name:",
    fill="#0B2F9F",
    font=("Times New Roman Bold", 15 * -1)
)

canvas.create_text(
    38.0,
    227.0,
    anchor="nw",
    text="Position:",
    fill="#0B2F9F",
    font=("Times New Roman Bold", 15 * -1)
)

canvas.create_text(
    53.0,
    261.0,
    anchor="nw",
    text="Email:",
    fill="#0B2F9F",
    font=("Times New Roman Bold", 15 * -1)
)

canvas.create_text(
    28.0,
    295.0,
    anchor="nw",
    text="Password:",
    fill="#0B2F9F",
    font=("Times New Roman Bold", 15 * -1)
)
#Fisrt Name
entry_image_1 = PhotoImage(
    file=relative_to_assets("F_name_data.png"))
entry_bg_1 = canvas.create_image(
    193.5,
    157.0,
    image=entry_image_1
)
F_name_data = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
F_name_data.place(
    x=109.0,
    y=145.0,
    width=169.0,
    height=22.0
)
#Last Name
entry_image_2 = PhotoImage(
    file=relative_to_assets("L_name_data.png"))
entry_bg_2 = canvas.create_image(
    193.5,
    197.0,
    image=entry_image_2
)
L_name_data = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
L_name_data.place(
    x=109.0,
    y=185.0,
    width=169.0,
    height=22.0
)
#Position
entry_image_3 = PhotoImage(
    file=relative_to_assets("Position_data.png"))
entry_bg_3 = canvas.create_image(
    193.5,
    229.0,
    image=entry_image_3
)

Position_data = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
Position_data.place(
    x=109.0,
    y=217.0,
    width=169.0,
    height=22.0
)
#email
entry_image_4 = PhotoImage(
    file=relative_to_assets("email_data.png"))
entry_bg_4 = canvas.create_image(
    193.5,
    263.0,
    image=entry_image_4
)
email_data = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
email_data.place(
    x=109.0,
    y=251.0,
    width=169.0,
    height=22.0
)
#Password
entry_image_5 = PhotoImage(
    file=relative_to_assets("Password_data.png"))
entry_bg_5 = canvas.create_image(
    193.5,
    301.0,
    image=entry_image_5
)
Password_data = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
Password_data.place(
    x=109.0,
    y=289.0,
    width=169.0,
    height=22.0
)

canvas.create_text(
    78.0,
    100.0,
    anchor="nw",
    text="ADD EMPLOYEE",
    fill="#0B2F9F",
    font=("Times New Roman Bold", 20 * -1)
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("sm8.png"))
image_1 = canvas.create_image(
    160.0,
    50.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
