
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\charl\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\FINAL\assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x740")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 740,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    389.0,
    740.0,
    fill="#FFDB00",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("Add_employee.png"))
add_employee_button = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
add_employee_button.place(
    x=1060.0,
    y=691.0,
    width=219.89620971679688,
    height=43.96636199951172
)

button_image_2 = PhotoImage(
    file=relative_to_assets("dashboard_employee.png"))
dashboard_employee_button = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
dashboard_employee_button.place(
    x=0.0,
    y=269.4220275878906,
    width=389.2879638671875,
    height=49.19176483154297
)

canvas.create_rectangle(
    0.0,
    245.0,
    389.0,
    269.0,
    fill="#CABB11",
    outline="")

canvas.create_text(
    396.0,
    30.0,
    anchor="nw",
    text="EMPLOYEE",
    fill="#0F2F9F",
    font=("Times New Roman Bold", 60 * -1)
)

canvas.create_text(
    465.0,
    138.0,
    anchor="nw",
    text="Employee Name",
    fill="#000000",
    font=("Times New Roman Bold", 15 * -1)
)

canvas.create_text(
    700.0,
    138.0,
    anchor="nw",
    text="ID Number",
    fill="#000000",
    font=("Times New Roman Bold", 15 * -1)
)

canvas.create_text(
    900.0,
    138.0,
    anchor="nw",
    text="Position",
    fill="#000000",
    font=("Times New Roman Bold", 15 * -1)
)

canvas.create_text(
    1025.0,
    138.0,
    anchor="nw",
    text="Total Work Hours",
    fill="#000000",
    font=("Times New Roman Bold", 15 * -1)
)

canvas.create_text(
    1158.0,
    138.0,
    anchor="nw",
    text="No. of Absences",
    fill="#000000",
    font=("Times New Roman Bold", 15 * -1)
)

canvas.create_text(
    2.0,
    181.0,
    anchor="nw",
    text="ADMIN",
    fill="#000000",
    font=("Times New Roman", 50 * -1)
)

canvas.create_text(
    5.0,
    248.0,
    anchor="nw",
    text="Main",
    fill="#000000",
    font=("Times New Roman", 15 * -1)
)

absences_employee = PhotoImage(
    file=relative_to_assets("absences_employee.png"))
entry_bg_1 = canvas.create_image(
    1210.0,
    417.5,
    image=absences_employee
)
absences_employee_text = Text(
    bd=0,
    bg="#0F2F9F",
    fg="#000716",
    highlightthickness=0
)
absences_employee_text.place(
    x=1168.0,
    y=156.0,
    width=84.0,
    height=521.0
)

tw_hours_employee = PhotoImage(
    file=relative_to_assets("tw_hours_employee.png"))
entry_bg_2 = canvas.create_image(
    1085.0,
    417.5,
    image=tw_hours_employee
)
tw_hours_employee_text = Text(
    bd=0,
    bg="#0F2F9F",
    fg="#000716",
    highlightthickness=0
)
tw_hours_employee_text.place(
    x=1043.0,
    y=156.0,
    width=84.0,
    height=521.0
)

Id_number_employee = PhotoImage(
    file=relative_to_assets("Id_number_employee.png"))
entry_bg_3 = canvas.create_image(
    736.5,
    417.5,
    image=Id_number_employee
)
Id_number_employee_text = Text(
    bd=0,
    bg="#0F2F9F",
    fg="#000716",
    highlightthickness=0
)
Id_number_employee_text.place(
    x=662.0,
    y=156.0,
    width=149.0,
    height=521.0
)

position_employee = PhotoImage(
    file=relative_to_assets("position_employee.png"))
entry_bg_4 = canvas.create_image(
    927.5,
    417.5,
    image=position_employee
)
position_employee_text = Text(
    bd=0,
    bg="#0F2F9F",
    fg="#000716",
    highlightthickness=0
)
position_employee_text.place(
    x=856.0,
    y=156.0,
    width=143.0,
    height=521.0
)

employee_name = PhotoImage(
    file=relative_to_assets("employee_name.png"))
entry_bg_5 = canvas.create_image(
    516.5,
    417.5,
    image=employee_name
)
employee_name_text = Text(
    bd=0,
    bg="#0F2F9F",
    fg="#000716",
    highlightthickness=0
)
employee_name_text.place(
    x=415.0,
    y=156.0,
    width=203.0,
    height=521.0
)

#savemore photo
image_image_1 = PhotoImage(
    file=relative_to_assets("sm3.png"))
image_1 = canvas.create_image(
    179.0,
    81.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
