
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\charl\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\FINAL\assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x740")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 740,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    389.0,
    740.0,
    fill="#FFDB00",
    outline="")

attendance_button = PhotoImage(
    file=relative_to_assets("attendance_button.png"))
button_1 = Button(
    image=attendance_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=1025.0169677734375,
    y=643.7835693359375,
    width=232.98297119140625,
    height=49.19176483154297
)

employees_button = PhotoImage(
    file=relative_to_assets("employees_button.png"))
button_2 = Button(
    image=employees_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=783.1917114257812,
    y=643.7835693359375,
    width=232.98297119140625,
    height=49.19176483154297
)

dashboar_dashboard = PhotoImage(
    file=relative_to_assets("dashboard_dashboard.png"))
button_3 = Button(
    image=dashboar_dashboard,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=0.0,
    y=269.4220275878906,
    width=389.2879638671875,
    height=49.19176483154297
)

time_out_dashboard = PhotoImage(
    file=relative_to_assets("time_out_dashboard.png"))
entry_bg_1 = canvas.create_image(
    1065.5,
    514.5,
    image=time_out_dashboard
)
time_out_dashboard_text = Text(
    bd=0,
    bg="#0B2F9F",
    fg="#000716",
    highlightthickness=0
)
time_out_dashboard_text.place(
    x=891.0,
    y=417.0,
    width=349.0,
    height=193.0
)

time_in_dahsboard = PhotoImage(
    file=relative_to_assets("time_in_dashboard.png"))
entry_bg_2 = canvas.create_image(
    611.5,
    515.5,
    image=time_in_dahsboard
)
time_in_dashboard_text = Text(
    bd=0,
    bg="#FFDB00",
    fg="#000716",
    highlightthickness=0
)
time_in_dashboard_text.place(
    x=437.0,
    y=418.0,
    width=349.0,
    height=193.0
)

attendance_dashboard = PhotoImage(
    file=relative_to_assets("attendance_dashboard.png"))
entry_bg_3 = canvas.create_image(
    1065.5,
    271.0,
    image=attendance_dashboard
)
attendance_dashboard_text = Text(
    bd=0,
    bg="#FFDB00",
    fg="#000716",
    highlightthickness=0
)
attendance_dashboard_text.place(
    x=891.0,
    y=173.0,
    width=349.0,
    height=194.0
)

employees_dashboard = PhotoImage(
    file=relative_to_assets("employees_dashboard.png"))
entry_bg_4 = canvas.create_image(
    611.5,
    275.0,
    image=employees_dashboard
)
employees_dashboard_text = Text(
    bd=0,
    bg="#0B2F9F",
    fg="#000716",
    highlightthickness=0
)
employees_dashboard_text.place(
    x=437.0,
    y=177.0,
    width=349.0,
    height=194.0
)

canvas.create_rectangle(
    0.0,
    245.0,
    389.0,
    269.0,
    fill="#CABB11",
    outline="")

canvas.create_text(
    519.0,
    382.0,
    anchor="nw",
    text="CHECKED IN",
    fill="#000000",
    font=("Times New Roman", 30 * -1)
)

canvas.create_text(
    970.0,
    382.0,
    anchor="nw",
    text="CHECKED OUT",
    fill="#000000",
    font=("Times New Roman", 30 * -1)
)

canvas.create_text(
    529.0,
    135.0,
    anchor="nw",
    text="EMPLOYEES",
    fill="#000000",
    font=("Times New Roman", 30 * -1)
)

canvas.create_text(
    2.0,
    181.0,
    anchor="nw",
    text="ADMIN",
    fill="#000000",
    font=("Times New Roman", 50 * -1)
)

canvas.create_text(
    960.0,
    135.0,
    anchor="nw",
    text="ATTENDANCE",
    fill="#000000",
    font=("Times New Roman", 30 * -1)
)

canvas.create_text(
    5.0,
    248.0,
    anchor="nw",
    text="Main",
    fill="#000000",
    font=("Times New Roman", 15 * -1)
)

canvas.create_text(
    421.0,
    30.0,
    anchor="nw",
    text="DASHBOARD",
    fill="#0F2F9F",
    font=("Times New Roman Bold", 60 * -1)
)

#savemore photo
image_image_1 = PhotoImage(
    file=relative_to_assets("sm4.png"))
image_1 = canvas.create_image(
    179.0,
    81.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
