
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\charl\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\FINAL\assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x740")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 740,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    350.0,
    740.0,
    fill="#FFDB00",
    outline="")

canvas.create_rectangle(
    0.0,
    245.0,
    350.0,
    272.0,
    fill="#CABB11",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("dashboard_attendance.png"))
Dashboard_Attendance = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
Dashboard_Attendance.place(
    x=0.0,
    y=272.8150939941406,
    width=350.2614440917969,
    height=64.8882064819336
)

canvas.create_text(
    2.0,
    185.0,
    anchor="nw",
    text="ADMIN",
    fill="#000000",
    font=("Times New Roman", 50 * -1)
)

canvas.create_text(
    5.0,
    248.0,
    anchor="nw",
    text="Main",
    fill="#000000",
    font=("Times New Roman", 20 * -1)
)

canvas.create_text(
    415.0,
    175.0,
    anchor="nw",
    text="Date",
    fill="#0B2F9F",
    font=("Times New Roman", 20 * -1)
)

canvas.create_text(
    359.0,
    57.0,
    anchor="nw",
    text="ATTENDANCE",
    fill="#0B2F9F",
    font=("Times New Roman Bold", 60 * -1)
)

canvas.create_text(
    590.0,
    175.0,
    anchor="nw",
    text="Name",
    fill="#0B2F9F",
    font=("Times New Roman", 20 * -1)
)

canvas.create_text(
    780.0,
    175.0,
    anchor="nw",
    text="Position",
    fill="#0B2F9F",
    font=("Times New Roman", 20 * -1)
)

canvas.create_text(
    920.0,
    175.0,
    anchor="nw",
    text="Time In",
    fill="#0B2F9F",
    font=("Times New Roman", 20 * -1)
)

canvas.create_text(
    1165.0,
    175.0,
    anchor="nw",
    text="Total Hours",
    fill="#0B2F9F",
    font=("Times New Roman", 20 * -1)
)

canvas.create_text(
    1040.0,
    175.0,
    anchor="nw",
    text="Time Out",
    fill="#0B2F9F",
    font=("Times New Roman", 20 * -1)
)

Total_Hours_entry = PhotoImage(
    file=relative_to_assets("Total_Hours.png"))
entry_bg_1 = canvas.create_image(
    1212.5,
    469.5,
    image=Total_Hours_entry
)
Total_Hours_text = Text(
    bd=0,
    bg="#FFDB00",
    fg="#000716",
    highlightthickness=0
)
Total_Hours_text.place(
    x=1168.0,
    y=199.0,
    width=89.0,
    height=539.0
)

Time_out_entry = PhotoImage(
    file=relative_to_assets("Time_out.png"))
entry_bg_2 = canvas.create_image(
    1084.5,
    469.5,
    image=Time_out_entry
)
Time_Out_Text = Text(
    bd=0,
    bg="#FFDB00",
    fg="#000716",
    highlightthickness=0
)
Time_Out_Text.place(
    x=1040.0,
    y=199.0,
    width=89.0,
    height=539.0
)

Position_entry = PhotoImage(
    file=relative_to_assets("Position.png"))
entry_bg_3 = canvas.create_image(
    811.0,
    469.5,
    image=Position_entry
)
Position_text = Text(
    bd=0,
    bg="#FFDB00",
    fg="#000716",
    highlightthickness=0
)
Position_text.place(
    x=749.0,
    y=199.0,
    width=124.0,
    height=539.0
)

Time_in_entry = PhotoImage(
    file=relative_to_assets("Time_in.png"))
entry_bg_4 = canvas.create_image(
    956.0,
    469.5,
    image=Time_in_entry
)
Time_in_text = Text(
    bd=0,
    bg="#FFDB00",
    fg="#000716",
    highlightthickness=0
)
Time_in_text.place(
    x=911.0,
    y=199.0,
    width=90.0,
    height=539.0
)

Name_entry = PhotoImage(
    file=relative_to_assets("Name.png"))
entry_bg_5 = canvas.create_image(
    616.5,
    469.5,
    image=Name_entry
)
Name_text = Text(
    bd=0,
    bg="#FFDB00",
    fg="#000716",
    highlightthickness=0
)
Name_text.place(
    x=523.0,
    y=199.0,
    width=187.0,
    height=539.0
)

Date_entry = PhotoImage(
    file=relative_to_assets("Date.png"))
entry_bg_6 = canvas.create_image(
    429.5,
    469.5,
    image=Date_entry
)
Date_text = Text(
    bd=0,
    bg="#FFDB00",
    fg="#000716",
    highlightthickness=0
)
Date_text.place(
    x=375.0,
    y=199.0,
    width=109.0,
    height=539.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("sm2.png"))
image_1 = canvas.create_image(
    179.0,
    81.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
