
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\charl\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\FINAL\assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("380x320")
window.configure(bg = "#FFDB00")


canvas = Canvas(
    window,
    bg = "#FFDB00",
    height = 320,
    width = 380,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("username_admin.png"))
entry_bg_1 = canvas.create_image(
    229.5,
    151.0,
    image=entry_image_1
)
username_admin = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
username_admin.place(
    x=121.0,
    y=137.0,
    width=217.0,
    height=28.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("password_admin.png"))
entry_bg_2 = canvas.create_image(
    229.5,
    194.0,
    image=entry_image_2
)
password_admin = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
password_admin.place(
    x=121.0,
    y=179.0,
    width=217.0,
    height=28.0
)

canvas.create_text(
    105.0,
    98.0,
    anchor="nw",
    text="ADMIN LOGIN",
    fill="#0B2F9F",
    font=("Times New Roman Bold", 25 * -1)
)

canvas.create_text(
    22.0,
    185.0,
    anchor="nw",
    text="PASSWORD:",
    fill="#0B2F9F",
    font=("Times New Roman Bold", 15 * -1)
)

canvas.create_text(
    22.0,
    143.0,
    anchor="nw",
    text="USERNAME:",
    fill="#0B2F9F",
    font=("Times New Roman Bold", 15 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("login_admin.png"))
login_admin = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
login_admin.place(
    x=171.0,
    y=221.0,
    width=117.0,
    height=24.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("sm6.png"))
image_1 = canvas.create_image(
    188.0,
    52.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
