
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\charl\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\FINAL\assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x740")
window.configure(bg = "#FFDB00")


canvas = Canvas(
    window,
    bg = "#FFDB00",
    height = 740,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
#Number of absent
no_of_absent = PhotoImage(
    file=relative_to_assets("no_of_absent.png"))
entry_bg_1 = canvas.create_image(
    1065.5,
    430.5,
    image=no_of_absent
)
no_of_absent_text = Text(
    bd=0,
    bg="#0F2F9F",
    fg="#000716",
    highlightthickness=0
)
no_of_absent_text.place(
    x=896.0,
    y=299.0,
    width=339.0,
    height=261.0
)
#number of present
no_of_present = PhotoImage(
    file=relative_to_assets("no_of_present.png"))
entry_bg_2 = canvas.create_image(
    610.0,
    430.5,
    image=no_of_present
)
no_of_present_text = Text(
    bd=0,
    bg="#0B2F9F",
    fg="#000716",
    highlightthickness=0
)
no_of_present_text.place(
    x=441.0,
    y=299.0,
    width=338.0,
    height=261.0
)
#total worked hours
tw_hours_user = PhotoImage(
    file=relative_to_assets("tw_hours_user.png"))
entry_bg_3 = canvas.create_image(
    191.5,
    430.5,
    image=tw_hours_user
)
tw_hours_user_text = Text(
    bd=0,
    bg="#0B2F9F",
    fg="#000716",
    highlightthickness=0
)
tw_hours_user_text.place(
    x=22.0,
    y=299.0,
    width=339.0,
    height=261.0
)
#Detail entry
user_details = PhotoImage(
    file=relative_to_assets("user_details.png"))
entry_bg_4 = canvas.create_image(
    348.5,
    122.5,
    image=user_details
)
user_details_text = Text(
    bd=0,
    bg="#0B2F9F",
    fg="#000716",
    highlightthickness=0
)
user_details_text.place(
    x=22.0,
    y=40.0,
    width=653.0,
    height=163.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("sm5.png"))
image_1 = canvas.create_image(
    964.0,
    133.0,
    image=image_image_1
)
#Logout
button_image_1 = PhotoImage(
    file=relative_to_assets("Logout_button_user.png"))
logout_button = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
logout_button.place(
    x=1022.3297119140625,
    y=679.1943359375,
    width=238.67025756835938,
    height=50.80557632446289
)
#Check Out
button_image_2 = PhotoImage(
    file=relative_to_assets("time_out_button.png"))
time_out_button = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
time_out_button.place(
    x=22.0,
    y=643.863037109375,
    width=219.89620971679688,
    height=43.96636199951172
)
#Check in
button_image_3 = PhotoImage(
    file=relative_to_assets("time_in_button.png"))
time_in_button = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
time_in_button.place(
    x=22.0,
    y=584.26416015625,
    width=219.89620971679688,
    height=43.96636199951172
)

canvas.create_text(
    23.0,
    255.0,
    anchor="nw",
    text="Total Worked Hours",
    fill="#000000",
    font=("Times New Roman Bold", 35 * -1)
)

canvas.create_text(
    465.0,
    255.0,
    anchor="nw",
    text="Number of Present",
    fill="#000000",
    font=("Times New Roman Bold", 35 * -1)
)

canvas.create_text(
    925.0,
    255.0,
    anchor="nw",
    text="Number of Absent",
    fill="#000000",
    font=("Times New Roman Bold", 35 * -1)
)
window.resizable(False, False)
window.mainloop()
